In [1]:
import os
import numpy as np
import pandas as pd
import pickle as pkl
import random

# 오리지널 데이터

In [2]:
data_df = pd.read_csv("../data/train/train.tsv", sep="\t", header=None)
data_df

,0,1,2,3,4,5,6,7,8
0,wikipedia-24896-25-30-33-19-21,영국에서 사용되는 스포츠 유틸리티 자동차의 브랜드로는 랜드로버(Land Rover)...,랜드로버,30,33,자동차,19,21,단체:제작
1,wikipedia-12728-224-5-7-42-44,"선거에서 민주당은 해산 전 의석인 230석에 한참 못 미치는 57석(지역구 27석,...",민주당,5,7,27석,42,44,관계_없음
2,wikipedia-28460-3-0-7-9-12,유럽 축구 연맹(UEFA) 집행위원회는 2014년 1월 24일에 열린 회의를 통해 ...,유럽 축구 연맹,0,7,UEFA,9,12,단체:별칭
3,wikipedia-11479-37-24-26-3-5,"용병 공격수 챠디의 부진과 시즌 초 활약한 강수일의 침체, 시즌 중반에 영입한 세르...",강수일,24,26,공격수,3,5,인물:직업/직함
4,wikipedia-15581-6-0-2-32-40,람캄행 왕은 1237년에서 1247년 사이 수코타이의 왕 퍼쿤 씨 인트라팃과 쓰엉 ...,람캄행,0,2,퍼쿤 씨 인트라팃,32,40,인물:부모님
...,...,...,...,...,...,...,...,...,...
8995,wikipedia-5414-12-15-21-0-4,2002년 FIFA 월드컵 사우디아라비아와의 1차전에서 독일은 8-0으로 승리하였는...,사우디아라비아,15,21,2002년,0,4,관계_없음
8996,wikipedia-10384-4-12-14-0-1,일본의 2대 메이커인 토요타와 닛산은 시장 점유율을 높이기 위한 신차 개발을 계속하...,토요타,12,14,일본,0,1,단체:본사_국가
8997,wikipedia-25913-6-8-10-93-106,방호의의 손자 방덕룡(方德龍)은 1588년(선조 21년) 무과에 급제하고 낙안군수로...,방덕룡,8,10,선무원종공신(宣武原從功臣),93,106,인물:직업/직함
8998,wikitree-12062-15-0-3-46-47,LG전자는 올해 초 국내시장에 출시한 2020년형 ‘LG 그램’ 시리즈를 이달부터 ...,LG전자,0,3,북미,46,47,관계_없음
8999,wikitree-21265-0-16-18-20-21,전남도의회 안전건설소방위원회 차영수 의원(강진1)은 지난 14일 설 명절을 앞두고 ...,차영수,16,18,의원,20,21,인물:직업/직함

In [3]:
with open("../data/label_type.pkl", "rb") as lt:
    label_encoder = pkl.load(lt)

In [4]:
label_counts = {k: data_df[8].value_counts()[k] for k in label_encoder.keys()}
label_counts

{'관계_없음': 4440,
 '인물:배우자': 92,
 '인물:직업/직함': 553,
 '단체:모회사': 44,
 '인물:소속단체': 680,
 '인물:동료': 186,
 '단체:별칭': 231,
 '인물:출신성분/국적': 209,
 '인물:부모님': 164,
 '단체:본사_국가': 115,
 '단체:구성원': 815,
 '인물:기타_친족': 58,
 '단체:창립자': 45,
 '단체:주주': 11,
 '인물:사망_일시': 45,
 '단체:상위_단체': 335,
 '단체:본사_주(도)': 23,
 '단체:제작': 165,
 '인물:사망_원인': 7,
 '인물:출생_도시': 4,
 '단체:본사_도시': 136,
 '인물:자녀': 84,
 '인물:제작': 56,
 '단체:하위_단체': 80,
 '인물:별칭': 103,
 '인물:형제/자매/남매': 52,
 '인물:출생_국가': 8,
 '인물:출생_일시': 36,
 '단체:구성원_수': 9,
 '단체:자회사': 5,
 '인물:거주_주(도)': 12,
 '단체:해산일': 15,
 '인물:거주_도시': 26,
 '단체:창립일': 67,
 '인물:종교': 15,
 '인물:거주_국가': 27,
 '인물:용의자': 11,
 '인물:사망_도시': 3,
 '단체:정치/종교성향': 18,
 '인물:학교': 9,
 '인물:사망_국가': 1,
 '인물:나이': 5}

# 추가 데이터

In [5]:
extra_data = pd.read_csv("../data/train/extras.tsv", sep="\t", header=None)
# extra_data_1 = pd.read_csv("../data/train/19_bornIn_city.tsv", sep="\t", header=None)
# extra_data_2 = pd.read_csv("../data/train/26_bornIn_country.tsv", sep="\t", header=None)
# extra_data_3 = pd.read_csv("../data/train/37_dienIn_city.tsv", sep="\t", header=None)
# extra_data_4 = pd.read_csv("../data/train/40_dienIn_country.tsv", sep="\t", header=None)
# extra_data = pd.concat([extra_data_0, extra_data_1, extra_data_2, extra_data_3, extra_data_4])
extra_data

,0,1,2,3,4,5,6,7,8
0,from train_csv 5,"카터 는 이집트 와 이스라엘 을 조정 하 여 , 캠프 데이비드 에서 안와르 사다트 ...",안와르 사다트,38,44,이집트,5,7,인물:출신성분/국적
1,from train_csv 8,"카터 는 이집트 와 이스라엘 을 조정 하 여 , 캠프 데이비드 에서 안와르 사다트 ...",캠프데이비드 협정,78,86,이스라엘,11,14,단체:구성원
2,from train_csv 9,"카터 는 이집트 와 이스라엘 을 조정 하 여 , 캠프 데이비드 에서 안와르 사다트 ...",캠프데이비드 협정,78,86,이집트,5,7,단체:구성원
3,from train_csv 11,"카터 는 이집트 와 이스라엘 을 조정 하 여 , 캠프 데이비드 에서 안와르 사다트 ...",메나헴 베긴,52,57,이스라엘,11,14,인물:출신성분/국적
4,from train_csv 65,선거 전 까지 각축전 을 벌인 유력 한 후보 는 15 대 대통령 선거 에 나와 김대...,한나라당,63,66,이회창,75,77,단체:구성원
...,...,...,...,...,...,...,...,...,...
229606,from dev_csv 99215,"2. ""사슴여인"" (박건호 작사 / 계동균 작곡) – 03:24",박건호,11,13,사슴여인,4,7,인물:제작
229607,from dev_csv 99216,"9. ""안녕히 계세요"" (장덕 작사 / 장덕 작곡) - 02:06",장덕,14,15,안녕히 계세요,4,10,인물:제작
229608,from dev_csv 99217,"2009년, 블런트는 장마크 발레가 감독을 맡고 줄리언 펠로스가 각본을 쓴 《영 빅...",줄리언 펠로스,27,33,영 빅토리아,43,48,인물:제작
229609,from dev_csv 99218,2008년 저드 애퍼토가 제작하고 세스 로건과 에번 골드버그가 각본을 맡은 코미디 ...,에번 골드버그,26,32,파인애플 익스프레스,50,59,인물:제작
229610,from dev_csv 99219,"영화 《라이터를 켜라》,《귀신이 산다》의 장항준, 《그해 여름》의 김은희 작가가 공...",장항준,23,25,귀신이 산다,14,19,인물:제작

In [6]:
extra_counts = extra_data[8].value_counts()
extra_counts

인물:출신성분/국적    77850
인물:직업/직함      34615
단체:창립일        27757
인물:제작         16601
단체:제작         15039
단체:구성원        13779
인물:배우자        11205
인물:자녀         10461
인물:기타_친족       9650
인물:부모님         4566
단체:상위_단체       3436
인물:학교          2062
단체:정치/종교성향     1591
인물:소속단체         875
단체:창립자          124
Name: 8, dtype: int64

# 데이터 추출하기

In [11]:
max_pick_num = int(np.mean(list(label_counts.values())) * 1.2)
max_pick_num

257

In [12]:
tgt_data = pd.DataFrame(columns=data_df.columns)
for k, v in extra_counts.items():
    if max_pick_num - label_counts[k] <= 0:
        continue
    pick_num = min(max_pick_num - label_counts[k], extra_counts[k])
    sample = np.random.choice(extra_data.loc[extra_data[8] == k, :].index, size=pick_num)
    pick_data = extra_data.iloc[sample, :]
    tgt_data = pd.concat([tgt_data, pick_data])
tgt_data

,0,1,2,3,4,5,6,7,8
158681,from train_csv 707971,남석훈 ( 1939 년 ~ ) 는 대한민국 의 배우 이 다 .,남석훈,1,3,대한민국,20,23,인물:출신성분/국적
162527,from train_csv 725851,"아오키 마유미 ( , 1953 년 5 월 1 일 ~ ) 는 일본 의 수영 선수 이...",아오키 마유미,1,7,일본,34,35,인물:출신성분/국적
178667,from train_csv 821529,이 문서 는 대한민국 제 19 대 대통령 문재인 의 대한민국 제 19 대 대통령 선...,문재인,23,25,대한민국,7,10,인물:출신성분/국적
119868,from train_csv 506237,"앨리슨 브리 셔머혼 ( Alison Brie Schermerhorn , 1982 ...",앨리슨 브리,1,6,미국,64,65,인물:출신성분/국적
13531,from train_csv 49715,남송 ( 南宋 ) 남송 효종 ( 孝宗 ) 6 년,남송 효종,11,15,남송,1,2,인물:출신성분/국적
...,...,...,...,...,...,...,...,...,...
222002,from train_csv 969351,아버지는 20세기 폭스의 창립자인 대릴 F. 재넉이고 어머니는 배우 버지니아 폭스이다.,대릴 F. 재넉,19,26,20세기 폭스,5,11,단체:창립자
220950,from train_csv 918303,1920년 아디다스의 창업자 아돌프 다슬러가 스포츠화를 최초로 제작하게 된다.,아돌프 다슬러,17,23,아디다스,7,10,단체:창립자
229016,from dev_csv 8332,"낸시 월턴 로리(Nancy Walton Laurie, 1951년 5월 15일 ~ )...",샘 월턴,66,69,월마트,58,60,단체:창립자
229016,from dev_csv 8332,"낸시 월턴 로리(Nancy Walton Laurie, 1951년 5월 15일 ~ )...",샘 월턴,66,69,월마트,58,60,단체:창립자
222002,from train_csv 969351,아버지는 20세기 폭스의 창립자인 대릴 F. 재넉이고 어머니는 배우 버지니아 폭스이다.,대릴 F. 재넉,19,26,20세기 폭스,5,11,단체:창립자

In [13]:
tgt_data[8].value_counts()

인물:학교         248
단체:정치/종교성향    239
인물:제작         201
인물:기타_친족      199
단체:창립일        190
인물:자녀         173
인물:배우자        165
단체:창립자        124
인물:부모님         93
단체:제작          92
인물:출신성분/국적     48
Name: 8, dtype: int64

In [80]:
augmented_data = pd.concat([data_df, tgt_data])
augmented_data.to_csv("../data/train/augmented.tsv", sep="\t", header=None, index=False)